[package]
name = "mandelbrot-rust"
version = "0.1.0"
authors = ["hanksterhan <henryhan62@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.15.0"